//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class articles
{
    public string userID { get; set; }
    public int articleID { get; set; }
    public string articleTitle { get; set; }
    public string articleContent { get; set; }
    public string articleClass { get; set; }
    public System.DateTime pushTime { get; set; }
    public int clockCount { get; set; }

    public virtual classes classes { get; set; }
}

public partial class classes
{
    public classes()
    {
        this.articles = new HashSet<articles>();
    }

    public string articleClass { get; set; }

    public virtual ICollection<articles> articles { get; set; }
}

public partial class reviews
{
    public int reviewID { get; set; }
    public string userID { get; set; }
    public string articleTitle { get; set; }
    public int articleID { get; set; }
    public string penName { get; set; }
    public string reviewContent { get; set; }
    public string reviewRespond { get; set; }
}

public partial class users
{
    public string userID { get; set; }
    public string userPassword { get; set; }
    public string userPicture { get; set; }
    public string userSex { get; set; }
    public Nullable<System.DateTime> userBirthday { get; set; }
    public string userEmail { get; set; }
}
